// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var CircleView, circleView_tpl, wifi;
    wifi = require('./lib/wifiscan');
    circleView_tpl = require('hbs!./circle');
    return CircleView = Backbone.View.extend({
      className: 'handsome-jump center',
      events: {
        'click #refresh': 'refreshIP'
      },
      refreshIP: function() {
        return wifi.scan();
      },
      drawCircle: function() {
        var $c, $circle, $handsomeJump, $inner, innerWidth, _results;
        console.log('resized');
        $circle = this.$(".circle");
        $inner = $circle;
        $handsomeJump = this.$(".handsome-jump");
        innerWidth = $circle.width();
        $circle.css({
          height: innerWidth,
          width: innerWidth
        });
        console.log($circle, innerWidth);
        while ($inner.width() > 300) {
          console.log($inner.width());
          $c = $("<div class=\"circle-inner center\" />");
          $inner.append($c);
          $inner = $c;
        }
        this.$('.circle-inner').last().append('<div class="myself center" />');
        _results = [];
        while ($(".connected>li").length < 40) {
          _results.push($(".connected").append("<li></li>"));
        }
        return _results;
      },
      initialize: function() {
        return console.log('initialize');
      },
      render: function() {
        var tpl;
        console.log('render');
        tpl = circleView_tpl();
        this.$el.append(tpl);
        this.drawCircle();
        return this.refreshIP();
      },
      remove: function() {
        return console.log('remove');
      }
    });
  });

}).call(this);
