// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var CircleView, circleView_tpl;
    circleView_tpl = require('hbs!./circle');
    return CircleView = Backbone.View.extend({
      className: 'handsome-jump center',
      resized: function() {
        var $c, $circle, $handsomeJump, $inner, innerWidth;
        console.log('resized');
        $circle = this.$(".circle");
        $inner = $circle;
        $handsomeJump = this.$(".handsome-jump");
        innerWidth = $('body').width();
        $circle.css({
          height: innerWidth,
          width: innerWidth
        });
        console.log($circle, innerWidth);
        while ($inner.width() > 300) {
          console.log($inner.width());
          $c = $("<div class=\"circle-inner center\" />");
          $inner.append($c);
          $inner = $c;
        }
        return $circle.css({
          marginTop: -($circle.height() - $handsomeJump.height()) / 2 + 500
        });
        /*
              while $(".connected>.avator").length < 256
                $(".connected").append "<li class=\"avator img-circle\" style=\"background-image:url(https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash4/372355_582724207_361817571_q.jpg)\"></li>"
        */

      },
      initialize: function() {
        return console.log('initialize');
      },
      render: function() {
        var tpl;
        console.log('render');
        tpl = circleView_tpl();
        this.$el.append(tpl);
        return this.resized();
      },
      remove: function() {
        return console.log('remove');
      }
    });
  });

}).call(this);
