// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var CircleView, circleView, wifi;
    wifi = require('./lib/wifiscan');
    CircleView = require('./circleView');
    circleView = new CircleView();
    $('body').append(circleView.$el);
    circleView.render();
    return wifi.scanWorker('10.116.220.140');
  });

}).call(this);
