// Generated by CoffeeScript 1.3.3
(function() {
  var AJAX, Req, log,
    _this = this;

  AJAX = {
    get: function(url) {
      var xhr;
      try {
        xhr = new XMLHttpRequest();
        xhr.open("GET", url, false);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.timeout = 500;
        xhr.onreadystatechange = function() {
          if (xhr.readyState === 4 ? xhr.status === 200 : void 0) {
            return postMessage(xhr.responseText);
          }
        };
        return xhr.send(null);
      } catch (e) {
        return log("AJAX.get(" + url + ") error");
      }
    }
  };

  Req = {
    port: 8080,
    getStatus: function(ip) {
      var url;
      url = "" + ip + ":" + this.port + "/getstatus";
      log(url);
      return AJAX.get(url, function(res) {
        return log(res);
      });
    }
  };

  this.onmessage = function(e) {
    var data, ip, msgType, _i, _len;
    data = e.data;
    msgType = data.msgType;
    switch (msgType) {
      case 'data':
        data = data[data.msgType];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          ip = data[_i];
          Req.getStatus(ip);
        }
        log(data);
    }
    return log('postMessage from worker ok');
  };

  log = function(gg) {
    return _this.postMessage({
      msgType: 'debug',
      debug: gg
    });
  };

}).call(this);
