// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var wifiscan;
    return wifiscan = {
      scan: function(privateIP) {
        var i, scanIPList, sp_ip, sp_part1, sp_part2, _i;
        sp_ip = privateIP.split('.');
        sp_part1 = sp_ip.splice(0, 3);
        sp_part2 = sp_ip[3];
        scanIPList = [];
        for (i = _i = 1; _i <= 255; i = ++_i) {
          scanIPList.push(sp_part1.join('.') + ("." + i));
        }
        console.log(sp_ip);
        console.log(scanIPList);
        return scanIPList;
      }
    };
  });

}).call(this);
